export {default as Completed} from "./Completed";
export {default as Friends} from "./Friends";
export {default as InTransit} from "./InTransit";
export {default as OnHold} from "./OnHold";
export {default as Primary} from "./Primary";
export {default as Processing} from "./Processing";
export {default as Rejected} from "./Rejected";
export {default as Social} from "./Social";
export {default as Work} from "./Work";
